variables:
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
        - template: templates/build.yaml
  - stage: Tests
    jobs:
      - job:
        strategy:
          matrix:
            'Ubuntu | PowerShell 7':
              vmImage: ubuntu-18.04
            'macOS | PowerShell 7':
              vmImage: macOS-10.15
            'Windows | PowerShell 7':
              vmImage: windows-latest
        pool:
          vmImage: $[variables['vmImage']]
        steps:
        - template: templates/tests.yaml
      - job:
        strategy:
          matrix:
            'Windows | PowerShell 5.1':
              vmImage: windows-latest
              useWinPS: true
        pool:
          vmImage: $[ variables['vmImage'] ]
        steps:
        - template: templates/tests.yaml
          parameters:
            useWinPS: true
